mkdir -p '12_Angry_Men'
mkdir -p 'Good.Omens.S02.WEBDL.1080p.Rus.Eng'
mkdir -p 'Grinch.pohititel.Rozhdestva.2000.DUAL.BDRip.XviD.AC3.-HQCLUB'
mkdir -p 'Horoshij.Plohoj.Zloj.1966.DUAL.BDRip.XviD.AC3.-AllFilms'
mkdir -p 'Limitless.2011.Unrated.Extended.Cut.BDRip.Dub.Eng.Subs_by_LBS'
mkdir -p 'Miracle.Workers.S04.WEBDL.1080p.Rus.Eng'
mkdir -p 'MOSCOW_NOT_BELIEVE_IN_TEARS'
mkdir -p 'Obyknovennoe chudo'
mkdir -p "Pretend.It's.a.City.S01.WEB-DLRip"
mkdir -p 'Sex Education'
mkdir -p 'Sex Education (Season 4) WEB-DLRip'
mkdir -p 'Sluzhebnyj roman'
mkdir -p 'The.Kings.Speech.2010.DUAL.BDRip.2,18Gb.XviD.AC3'
mkdir -p 'The.Piano.Teacher.2001.bdrip_[2.18]_[teko]'
mkdir -p 'TRI TOLST'
mkdir -p "Д'Артаньян и три мушкетера HDTVRip"
mkdir -p 'Импостер_2023_WEB-DLRip'
mkdir -p 'Кибердеревня.(2023).WEBRip.(AVC).Files-x'
mkdir -p 'О.чём.говорят.мужчины.Простые.удовольствия.Сериал.WEB.1080p-ylnian'
mkdir -p 'Отступники_2006-BDRip-AVC'
mkdir -p 'Под электрическими облаками'
mkdir -p 'Продавцы боли_2023_WEB-DLRip'
mkdir -p 'Русь изначальная_2.18'
mkdir -p 'Чародеи (2 серии) 1982г. Константин Бромберг. HDTV 1080i'
touch 'A Beautiful Mind (2001) DVDRip-AVC Fullscreen.mkv'
touch 'American Beauty (1999) Open Matte WEB-DLRip-AVC.mkv'
touch 'Angel Heart.HQBDRip-AVC.PT.mkv'
touch 'Apokalipsis.Segodnja.1979.HDRip.MVO.avi'
touch 'Bessmertnyj.2022.AMZN.WEB-DLRip.AVC.mkv'
touch 'Bicentennial.Man.1999.hdtvrip.dexter_lex.avi'
touch 'Blue Velvet.1986.HQBDRip-AVC.PT.mkv'
touch 'Brilliantovaya.ruka.1968.BDRip.AVC.mkv'
touch 'Bullet Train (2022) BDRip.mkv'
touch 'Casino.1995.DVDRip-AVC.Fullscreen.mkv'
touch 'Dead.Poets.Society.1989.BDRip-AVC.mkv'
touch 'Durnye.dengi.2023.MA.WEB-DLRip.AVC.mkv'
touch 'Equilibrium_(2002).BDRip-AVC.aac.Dub.Eng.Sub.[All.Films][RG].mkv'
touch 'Eyes.Wide.Shut.1999.x264.BDR.tRuAVC.mkv'
touch 'Goodfellas.1990.720p.BluRay.11xRus.Eng-DON.mkv'
touch 'Ironia.Sudby.1.1975.O.DVDRip.2800.MediaClub.CurHaJI.avi'
touch 'Ivan_Vasilevich_menyaet_professiu_1973_BDRip.avi'
touch 'Karnavalnaya.noch.1956.BDRip.AVC.mkv'
touch 'Kruche.nekuda.2023.WEB-DLRip.AVC.mkv'
touch 'Luchshee.Predlojenie.2013.Dual.BDRip-AVC.mkv'
touch 'Maverick_HDTVRip_[rutracker.org]_by_Scarabey.avi'
touch 'Memoirs of a Geisha (HD).m4v'
touch 'Misery.1990.1080p.BluRay.3xRus.Eng.HDCLUB.mkv'
touch 'Nogti.2023.ATVP.WEB-DLRip.AVC.mkv'
touch 'Odin_doma_1990_BDRip_[REMASTERED]_by_Dalemake.avi'
touch 'Oldboy.2003.720p.BluRay.IIIKOJIO3ABP.mkv'
touch 'Operatsiya.Y.1965.BDRip.AVC.mkv'
touch 'Polosatyy.reys.1961.BDRip.AVC.mkv'
touch 'Pretty_Woman.avi'
touch 'Reservoir Dogs (1992) BDRip-AVC.mkv'
touch 'Shestoe_chuvstvo_1999_BDRip_by_Dalemake.avi'
touch 'The Equalizer.2014.WEB-DLRip.XviD.DUB.DD.2.0.avi'
touch 'The.Nightmare.Before.Christmas.1993.Blu-ray.1080p.x264-NiP.6xRus.Eng.mkv'
touch 'The.Pink.Panther.1963.1080p.BluRay.DTS.5.1.x264-iwok.2xRus.mkv'
touch 'The.Running.Man.1987.BDRip.MVO.All.Films.avi'
touch 'The.Shining.1980.2160p.UHD.BDRip.HDR10+.x265.DD+5.1-VoX.mkv'
touch 'The.Terminal.2004.WEB-DL.IVI.SDR.2060p-SOFCJ.mkv'
touch 'The.Untouchables.1987.BDRip.480p.VoiceOver.2400MB.mkv'
touch 'Tri.orisky.pro.Popelku.1973.BDRip-AVC.OIV.mkv'
touch 'V.dzaze.tolko.devushki.1959.HDTVRip.x264.Dub.Eng.Sub.mkv'
touch 'Yolki_poslednie_2018_WEB-DLRip-AVC_by_Dalemake.mkv'
touch 'Ёлки 9 2022 WEB-DLRip.avi'
touch 'Бегущий по лезвию (Blade Runner) BDRip-AVC [by ale_x2008].mkv'
touch 'Буч Кэссиди и Сандэнс Кид.mkv'
touch 'Великий уравнитель 2.2018.WEB-DL.2160p.DV.mp4'
touch 'Вся президентская рать (1976) 1.46 Гб.avi'
touch 'Гремлины (Gremlins) BDRip-AVC [by ale_x2008].mkv'
touch 'Иди ко мне, детка_2023_WEB-DLRip-AVC.mkv'
touch 'Крепкий орешек-2.avi'
touch 'Мулан_2020_WEB-DLRip.avi'
touch 'Огни большого города (City Lights) [1931].avi'
touch 'Пианист.2002.BDRip.avi'
touch 'Пробуждение (1990) BDRip [СВ-Дубль].mkv'
touch 'Пять ночей с Фредди_2023_WEB-DLRip-AVC.mkv'
touch 'Санта Клаус (The Santa Clause) HDRip-AVC [by ale_x2008].mkv'
touch 'Семь жизней  (драма, триллер 2008 год).avi'
touch 'Служанка.2016.WEB-DL.2160p.HDR.mkv'
touch 'Храброе сердце.avi'
touch 'Шпион.2015.Unrated.WEB-DL.2160p.SDR.mkv'
touch '12_Angry_Men/12_Angry_Men.avi'
touch '12_Angry_Men/12_Angry_Men.srt'
touch '12_Angry_Men/12_Angry_Men_eng.srt'
touch 'Good.Omens.S02.WEBDL.1080p.Rus.Eng/Good.Omens.S02E01.WEBDL.1080p.RGzsRutracker.mkv'
touch 'Good.Omens.S02.WEBDL.1080p.Rus.Eng/Good.Omens.S02E02.WEBDL.1080p.RGzsRutracker.mkv'
touch 'Good.Omens.S02.WEBDL.1080p.Rus.Eng/Good.Omens.S02E03.WEBDL.1080p.RGzsRutracker.mkv'
touch 'Good.Omens.S02.WEBDL.1080p.Rus.Eng/Good.Omens.S02E04.WEBDL.1080p.RGzsRutracker.mkv'
touch 'Good.Omens.S02.WEBDL.1080p.Rus.Eng/Good.Omens.S02E05.WEBDL.1080p.RGzsRutracker.mkv'
touch 'Good.Omens.S02.WEBDL.1080p.Rus.Eng/Good.Omens.S02E06.WEBDL.1080p.RGzsRutracker.mkv'
touch 'Grinch.pohititel.Rozhdestva.2000.DUAL.BDRip.XviD.AC3.-HQCLUB/Grinch.pohititel.Rozhdestva.2000.DUAL.BDRip.XviD.AC3.-HQCLUB.avi'
touch 'Grinch.pohititel.Rozhdestva.2000.DUAL.BDRip.XviD.AC3.-HQCLUB/Grinch.pohititel.Rozhdestva.2000.DUAL.BDRip.XviD.AC3.-HQCLUB.ENG.SDH.srt'
touch 'Grinch.pohititel.Rozhdestva.2000.DUAL.BDRip.XviD.AC3.-HQCLUB/Grinch.pohititel.Rozhdestva.2000.DUAL.BDRip.XviD.AC3.-HQCLUB.ENG.srt'
touch 'Grinch.pohititel.Rozhdestva.2000.DUAL.BDRip.XviD.AC3.-HQCLUB/Grinch.pohititel.Rozhdestva.2000.DUAL.BDRip.XviD.AC3.-HQCLUB.RUS.SDH.srt'
touch 'Grinch.pohititel.Rozhdestva.2000.DUAL.BDRip.XviD.AC3.-HQCLUB/Grinch.pohititel.Rozhdestva.2000.DUAL.BDRip.XviD.AC3.-HQCLUB.RUS.srt'
touch 'Grinch.pohititel.Rozhdestva.2000.DUAL.BDRip.XviD.AC3.-HQCLUB/Grinch.pohititel.Rozhdestva.2000.DUAL.BDRip.XviD.AC3.-HQCLUB.UKR.srt'
touch 'Horoshij.Plohoj.Zloj.1966.DUAL.BDRip.XviD.AC3.-AllFilms/Horoshij.Plohoj.Zloj.1966.DUAL.BDRip.XviD.AC3.-AllFilms.avi'
touch 'Horoshij.Plohoj.Zloj.1966.DUAL.BDRip.XviD.AC3.-AllFilms/Horoshij.Plohoj.Zloj.1966.DUAL.BDRip.XviD.AC3.-AllFilms.ENG.srt'
touch 'Horoshij.Plohoj.Zloj.1966.DUAL.BDRip.XviD.AC3.-AllFilms/Horoshij.Plohoj.Zloj.1966.DUAL.BDRip.XviD.AC3.-AllFilms.RUS.CEE.srt'
touch 'Horoshij.Plohoj.Zloj.1966.DUAL.BDRip.XviD.AC3.-AllFilms/Horoshij.Plohoj.Zloj.1966.DUAL.BDRip.XviD.AC3.-AllFilms.RUS.R5.srt'
touch 'Horoshij.Plohoj.Zloj.1966.DUAL.BDRip.XviD.AC3.-AllFilms/Horoshij.Plohoj.Zloj.1966.DUAL.BDRip.XviD.AC3.-AllFilms.RUS.Somewax.srt'
touch 'Limitless.2011.Unrated.Extended.Cut.BDRip.Dub.Eng.Subs_by_LBS/Limitless.2011.Unrated.Extended.Cut.BDRip.Dub.Eng_by_LBS.avi'
touch 'Limitless.2011.Unrated.Extended.Cut.BDRip.Dub.Eng.Subs_by_LBS/Limitless.2011.Unrated.Extended.Cut.BDRip.Dub.Eng_by_LBS_Eng.srt'
touch 'Limitless.2011.Unrated.Extended.Cut.BDRip.Dub.Eng.Subs_by_LBS/Limitless.2011.Unrated.Extended.Cut.BDRip.Dub.Eng_by_LBS_Rus.srt'
touch 'Miracle.Workers.S04.WEBDL.1080p.Rus.Eng/Miracle.Workers.S04E09.WEBDL.1080p.RGzsRutracker.mkv'
touch 'Miracle.Workers.S04.WEBDL.1080p.Rus.Eng/Miracle.Workers.S04E10.WEBDL.1080p.RGzsRutracker.mkv'
touch 'Miracle.Workers.S04.WEBDL.1080p.Rus.Eng/~uTorrentPartFile_4456C8069.dat'
touch 'MOSCOW_NOT_BELIEVE_IN_TEARS/Moskva.slezam.ne.verit.1979.Ep01.BDRip.AVC.mkv'
touch 'MOSCOW_NOT_BELIEVE_IN_TEARS/Moskva.slezam.ne.verit.1979.Ep02.BDRip.AVC.mkv'
touch 'Obyknovennoe chudo/Part 1.avi'
touch 'Obyknovennoe chudo/Part 2.avi'
touch "Pretend.It's.a.City.S01.WEB-DLRip/S01E01.Pretend.It's.a.City.avi"
touch "Pretend.It's.a.City.S01.WEB-DLRip/S01E01.Pretend.It's.a.City.rus.srt"
touch "Pretend.It's.a.City.S01.WEB-DLRip/S01E02.Cultural.Affairs.avi"
touch "Pretend.It's.a.City.S01.WEB-DLRip/S01E02.Cultural.Affairs.rus.srt"
touch "Pretend.It's.a.City.S01.WEB-DLRip/S01E03.Metropolitan.Transit.avi"
touch "Pretend.It's.a.City.S01.WEB-DLRip/S01E03.Metropolitan.Transit.rus.srt"
touch "Pretend.It's.a.City.S01.WEB-DLRip/S01E04.Board.of.Estimate.avi"
touch "Pretend.It's.a.City.S01.WEB-DLRip/S01E04.Board.of.Estimate.rus.srt"
touch "Pretend.It's.a.City.S01.WEB-DLRip/S01E05.Department.of.Sports.&.Health.avi"
touch "Pretend.It's.a.City.S01.WEB-DLRip/S01E05.Department.of.Sports.&.Health.rus.srt"
touch "Pretend.It's.a.City.S01.WEB-DLRip/S01E06.Hall.of.Records.avi"
touch "Pretend.It's.a.City.S01.WEB-DLRip/S01E06.Hall.of.Records.rus.srt"
touch "Pretend.It's.a.City.S01.WEB-DLRip/S01E07.Library.Services.avi"
touch "Pretend.It's.a.City.S01.WEB-DLRip/S01E07.Library.Services.rus.srt"
mkdir -p 'Sex Education/Season 1'
mkdir -p 'Sex Education/Season 2'
mkdir -p 'Sex Education/Season 3'
mkdir -p 'Sex Education/Season 1/Eng'
mkdir -p 'Sex Education/Season 1/Rus'
touch 'Sex Education/Season 1/Sex.Education.S01E01.WEBRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 1/Sex.Education.S01E01.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Sex.Education.S01E02.WEBRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 1/Sex.Education.S01E02.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Sex.Education.S01E03.WEBRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 1/Sex.Education.S01E03.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Sex.Education.S01E04.WEBRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 1/Sex.Education.S01E04.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Sex.Education.S01E05.WEBRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 1/Sex.Education.S01E05.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Sex.Education.S01E06.WEBRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 1/Sex.Education.S01E06.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Sex.Education.S01E07.WEBRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 1/Sex.Education.S01E07.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Sex.Education.S01E08.WEBRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 1/Sex.Education.S01E08.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Eng/Sex.Education.S01E01.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Eng/Sex.Education.S01E02.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Eng/Sex.Education.S01E03.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Eng/Sex.Education.S01E04.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Eng/Sex.Education.S01E05.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Eng/Sex.Education.S01E06.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Eng/Sex.Education.S01E07.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Eng/Sex.Education.S01E08.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Rus/Sex.Education.S01E01.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Rus/Sex.Education.S01E02.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Rus/Sex.Education.S01E03.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Rus/Sex.Education.S01E04.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Rus/Sex.Education.S01E05.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Rus/Sex.Education.S01E06.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Rus/Sex.Education.S01E07.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 1/Rus/Sex.Education.S01E08.WEBRip.RGzsRutracker.[Wentworth_Miller].srt'
mkdir -p 'Sex Education/Season 2/Eng'
mkdir -p 'Sex Education/Season 2/Rus'
touch 'Sex Education/Season 2/Sex.Education.S02E01.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 2/Sex.Education.S02E01.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Sex.Education.S02E02.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 2/Sex.Education.S02E02.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Sex.Education.S02E03.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 2/Sex.Education.S02E03.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Sex.Education.S02E04.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 2/Sex.Education.S02E04.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Sex.Education.S02E05.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 2/Sex.Education.S02E05.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Sex.Education.S02E06.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 2/Sex.Education.S02E06.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Sex.Education.S02E07.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 2/Sex.Education.S02E07.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Sex.Education.S02E08.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 2/Sex.Education.S02E08.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Eng/Sex.Education.S02E01.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Eng/Sex.Education.S02E02.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Eng/Sex.Education.S02E03.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Eng/Sex.Education.S02E04.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Eng/Sex.Education.S02E05.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Eng/Sex.Education.S02E06.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Eng/Sex.Education.S02E07.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Eng/Sex.Education.S02E08.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Rus/Sex.Education.S02E01.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Rus/Sex.Education.S02E02.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Rus/Sex.Education.S02E03.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Rus/Sex.Education.S02E04.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Rus/Sex.Education.S02E05.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Rus/Sex.Education.S02E06.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Rus/Sex.Education.S02E07.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 2/Rus/Sex.Education.S02E08.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
mkdir -p 'Sex Education/Season 3/Eng'
mkdir -p 'Sex Education/Season 3/Rus'
touch 'Sex Education/Season 3/Sex.Education.S03E01.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 3/Sex.Education.S03E01.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Sex.Education.S03E02.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 3/Sex.Education.S03E02.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Sex.Education.S03E03.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 3/Sex.Education.S03E03.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Sex.Education.S03E04.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 3/Sex.Education.S03E04.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Sex.Education.S03E05.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 3/Sex.Education.S03E05.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Sex.Education.S03E06.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 3/Sex.Education.S03E06.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Sex.Education.S03E07.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 3/Sex.Education.S03E07.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Sex.Education.S03E08.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education/Season 3/Sex.Education.S03E08.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Eng/Sex.Education.S03E01.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Eng/Sex.Education.S03E02.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Eng/Sex.Education.S03E03.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Eng/Sex.Education.S03E04.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Eng/Sex.Education.S03E05.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Eng/Sex.Education.S03E06.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Eng/Sex.Education.S03E07.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Eng/Sex.Education.S03E08.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Rus/Sex.Education.S03E01.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Rus/Sex.Education.S03E02.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Rus/Sex.Education.S03E03.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Rus/Sex.Education.S03E04.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Rus/Sex.Education.S03E05.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Rus/Sex.Education.S03E06.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Rus/Sex.Education.S03E07.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education/Season 3/Rus/Sex.Education.S03E08.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
mkdir -p 'Sex Education (Season 4) WEB-DLRip/Eng'
mkdir -p 'Sex Education (Season 4) WEB-DLRip/Rus'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E01.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E01.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].Forced.srt'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E02.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E02.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].Forced.srt'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E03.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E03.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].Forced.srt'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E04.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E04.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].Forced.srt'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E05.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E05.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].Forced.srt'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E06.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E06.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].Forced.srt'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E07.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E07.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].Forced.srt'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E08.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].avi'
touch 'Sex Education (Season 4) WEB-DLRip/Sex.Education.S04E08.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].Forced.srt'
touch 'Sex Education (Season 4) WEB-DLRip/Eng/Sex.Education.S04E01.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Eng/Sex.Education.S04E02.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Eng/Sex.Education.S04E03.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Eng/Sex.Education.S04E04.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Eng/Sex.Education.S04E05.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Eng/Sex.Education.S04E06.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Eng/Sex.Education.S04E07.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Eng/Sex.Education.S04E08.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Rus/Sex.Education.S04E01.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Rus/Sex.Education.S04E02.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Rus/Sex.Education.S04E03.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Rus/Sex.Education.S04E04.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Rus/Sex.Education.S04E05.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Rus/Sex.Education.S04E06.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Rus/Sex.Education.S04E07.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sex Education (Season 4) WEB-DLRip/Rus/Sex.Education.S04E08.WEB-DLRip.RGzsRutracker.[Wentworth_Miller].srt'
touch 'Sluzhebnyj roman/Sluzhebnyj.roman.1977.Ep01.BDRip.AVC.mkv'
touch 'Sluzhebnyj roman/Sluzhebnyj.roman.1977.Ep02.BDRip.AVC.mkv'
touch 'The.Kings.Speech.2010.DUAL.BDRip.2,18Gb.XviD.AC3/The.Kings.Speech.2010.DUAL.BDRip.2,18Gb.XviD.AC3.avi'
touch 'The.Kings.Speech.2010.DUAL.BDRip.2,18Gb.XviD.AC3/The.Kings.Speech.2010.DUAL.BDRip.2,18Gb.XviD.AC3.eng full.srt'
touch 'The.Kings.Speech.2010.DUAL.BDRip.2,18Gb.XviD.AC3/The.Kings.Speech.2010.DUAL.BDRip.2,18Gb.XviD.AC3.rus full.srt'
touch 'The.Piano.Teacher.2001.bdrip_[2.18]_[teko]/The.Piano.Teacher.2001.bdrip_[2.18].avi'
touch 'The.Piano.Teacher.2001.bdrip_[2.18]_[teko]/The.Piano.Teacher.2001.bdrip_[2.18].sub.eng.srt'
touch 'The.Piano.Teacher.2001.bdrip_[2.18]_[teko]/The.Piano.Teacher.2001.bdrip_[2.18].sub.rus.srt'
touch 'The.Piano.Teacher.2001.bdrip_[2.18]_[teko]/The.Piano.Teacher.2001.bdrip_[2.18]_fre.ac3'
touch 'TRI TOLST/Tri tolstjaka (IceStorm).avi'
touch "Д'Артаньян и три мушкетера HDTVRip/Д'Артаньян и три мушкетера. 1 серия. HDTVRip.mkv"
touch "Д'Артаньян и три мушкетера HDTVRip/Д'Артаньян и три мушкетера. 2 серия. HDTVRip.mkv"
touch "Д'Артаньян и три мушкетера HDTVRip/Д'Артаньян и три мушкетера. 3 серия. HDTVRip.mkv"
touch 'Импостер_2023_WEB-DLRip/Импостер_2023_WEB-DLRip.avi'
touch 'Импостер_2023_WEB-DLRip/Импостер_2023_WEB-DLRip.srt'
touch 'Кибердеревня.(2023).WEBRip.(AVC).Files-x/06.Кибердеревня.(2023).WEBRip.(AVC).by.Серый1779.Files-x.mkv'
touch 'Кибердеревня.(2023).WEBRip.(AVC).Files-x/07.Кибердеревня.(2023).WEBRip.(AVC).by.Серый1779.Files-x.mkv'
touch 'Кибердеревня.(2023).WEBRip.(AVC).Files-x/08.Кибердеревня.(2023).WEBRip.(AVC).by.Серый1779.Files-x.mkv'
touch 'Кибердеревня.(2023).WEBRip.(AVC).Files-x/09.Кибердеревня.(2023).WEBRip.(AVC).by.Серый1779.Files-x.mkv'
touch 'Кибердеревня.(2023).WEBRip.(AVC).Files-x/10.Кибердеревня.(2023).WEBRip.(AVC).by.Серый1779.Files-x.mkv'
touch 'Кибердеревня.(2023).WEBRip.(AVC).Files-x/~uTorrentPartFile_F6DC6200.dat'
touch 'О.чём.говорят.мужчины.Простые.удовольствия.Сериал.WEB.1080p-ylnian/О.чём.говорят.мужчины.Простые.удовольствия.S01.E01.2023.WEB.1080p-ylnian.mkv'
touch 'О.чём.говорят.мужчины.Простые.удовольствия.Сериал.WEB.1080p-ylnian/О.чём.говорят.мужчины.Простые.удовольствия.S01.E02.2023.WEB.1080p-ylnian.mkv'
touch 'О.чём.говорят.мужчины.Простые.удовольствия.Сериал.WEB.1080p-ylnian/О.чём.говорят.мужчины.Простые.удовольствия.S01.E03.2023.WEB.1080p-ylnian.mkv'
touch 'О.чём.говорят.мужчины.Простые.удовольствия.Сериал.WEB.1080p-ylnian/О.чём.говорят.мужчины.Простые.удовольствия.S01.E04.2023.WEB.1080p-ylnian.mkv'
touch 'О.чём.говорят.мужчины.Простые.удовольствия.Сериал.WEB.1080p-ylnian/О.чём.говорят.мужчины.Простые.удовольствия.S01.E05.2023.WEB.1080p-ylnian.mkv'
touch 'О.чём.говорят.мужчины.Простые.удовольствия.Сериал.WEB.1080p-ylnian/О.чём.говорят.мужчины.Простые.удовольствия.S01.E06.2023.WEB.1080p-ylnian.mkv'
touch 'О.чём.говорят.мужчины.Простые.удовольствия.Сериал.WEB.1080p-ylnian/О.чём.говорят.мужчины.Простые.удовольствия.S01.E07.2023.WEB.1080p-ylnian.mkv'
touch 'О.чём.говорят.мужчины.Простые.удовольствия.Сериал.WEB.1080p-ylnian/О.чём.говорят.мужчины.Простые.удовольствия.S01.E08.2023.WEB.1080p-ylnian.mkv'
touch 'Отступники_2006-BDRip-AVC/Отступники (1) (1).mka'
touch 'Отступники_2006-BDRip-AVC/Отступники_2006-BDRip-AVC.mkv'
touch 'Под электрическими облаками/Under.Electric.Clouds.2015.720p.WEB-DL.Rus.HDCLUB.mkv'
touch 'Продавцы боли_2023_WEB-DLRip/Продавцы боли_2023_WEB-DLRip.avi'
touch 'Продавцы боли_2023_WEB-DLRip/Продавцы боли_2023_WEB-DLRip.srt'
touch 'Русь изначальная_2.18/Русь изначальная_2.18_1.avi'
touch 'Русь изначальная_2.18/Русь изначальная_2.18_2.avi'
touch 'Чародеи (2 серии) 1982г. Константин Бромберг. HDTV 1080i/01.Чародеи. 1-я серия. HDTV 1080i_MPA2.0,AC3,rus.ts'
touch 'Чародеи (2 серии) 1982г. Константин Бромберг. HDTV 1080i/02.Чародеи. 2-я серия. HDTV 1080i_MPA2.0,AC3,rus.ts'
